### ISSUE TITLE
List of preferred cat food

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#1]
## Value Proposition
**As a** cat owner 
**I need** to have a list of food my cat likes
**to be able to** help my memory out

## Description
![Bildschirmfoto 2022-03-04 um 17 22 36](https://user-images.githubusercontent.com/90187803/156902103-3f033f28-22b7-4aec-8e99-5bae899b0f07.png)

## Acceptance criteria
- [x] there is an explaining headline text, this is fixed at the top of the viewport
- [x] there is a list with a few entries
- [x] each entry contents 3 hard coded characteristics
- [x] each characteristics starts at a new line

## Tasks

- [x] Global Styles
- [x] components/Card 
  - [x] Storybook
  - [x] Tests 
  - [x] Styling
- [x] components/LikedFoodPage 
  - [x] Storybook
  - [x] Tests 
  - [x] Styling
- [x] Check accessibility
- [x] Add to App
- [x] Test on mobile phone
