### ISSUE TITLE
Add sort function to LikedFoodPage

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#16]
## Value Proposition 

**As a** cat owner  
**I need to** have a sorting function on the page of food my cat/s like/s
**to be able to** get a faster overview while shopping 

## Description

![Bildschirmfoto 2022-03-17 um 20 10 12](https://user-images.githubusercontent.com/90187803/158877982-46c99077-f1f1-4c31-bc53-f60bf47d0d08.png)

## Acceptance Criteria

- [x] clicking a button sorts the listitems according to the name of the button

## Tasks

- [x] New Component sorting button
  - [x] Storybook
  - [x] Styling
- [x] Add 3 Components to LikedFoodPage
- [x] Add sorting function 
- [x] Styling
- [x] Check accessibility
- [x] Adjust README
