### ISSUE TITLE
Add cat profile page

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#17]
## Value Proposition 

**As a** cat owner  
**I need to** have a page dedicated to my cat
**to be able to** save some information on it

## Description
![Bildschirmfoto 2022-03-17 um 22 52 25](https://user-images.githubusercontent.com/90187803/158900742-086d30dd-67cf-4afa-be0c-6d26f88df555.png)

## Acceptance Criteria

- [x] editable input fields
- [x] picture upload

## Tasks

- [x] new editable Form on a new page, at least three textfields
- [x] Add picture upload
- [x] Adjust Tests
- [x] Adjust Navigation
- [x] Add to App
- [x] Check accessibility
- [x] Update README
