### ISSUE TITLE
List of not preferred cat food - now included in userstory 3

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#2]
## Value proposition
As a cat owner 
I want to have a list of food my cat doesn 't like to eat 
in order to stop buying it 

## Description
![Bildschirmfoto 2022-03-03 um 11 46 04](https://user-images.githubusercontent.com/90187803/156549579-ff00b296-762c-4f4a-9eed-e2ceb17873a7.png)

## Acceptance criteria
- [ ] there is an explaining headline text, this is fixed at the top of the viewport
- [ ] there is a list with a few entries
- [ ] each entry contents 3 characteristics with hard-coded data
- [ ] each characteristics starts at a new line

note: a navigation is added in the very next user story to keep this userstory and the next one manageable

## Tasks
- [ ] Global Styles
- [ ] components/Card 
  - [ ] Storybook
  - [ ] Tests 
  - [ ] Code card-content h2-Element with a description list
  - [ ] Styling
- [ ] components/UnLikedFood 
   - [ ] Unordered list with cards as li-items
- [ ] Check accessibility
- [ ] Add to App
- [ ] Test on mobile phone

**Comment by ttaannjjaa** [comment]
content in another userstory, so this will be closed
