### ISSUE TITLE
Add CatInfoPage

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#22]
## Value Proposition 

**As a** cat owner  
**I need to** have a page with infos about cats
**to be able to** get such informations fast at any time

## Description
![Bildschirmfoto 2022-03-26 um 08 21 03](https://user-images.githubusercontent.com/90187803/160229351-3e1e35e6-be45-47ed-89de-4538bc08c8e0.png)

## Acceptance Criteria

- [ ] fetched data about cats a shown in a list of cards

## Tasks

- [ ] Add page
- [ ] Storybook
- [ ] Tests
- [ ] Styling
- [ ] Adjust Router
- [ ] Check accessibility
- [ ] Add to App
- [ ] Test on Mobile
- [ ] Adjust README
