### ISSUE TITLE
Improve UX - Modal Delete Dialog

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#26]
## Value Proposition 

**As a** user
**I need to** have a modal
**to be able to** delete list items not occasionally

## Description
![Bildschirmfoto 2022-03-29 um 09 52 58](https://user-images.githubusercontent.com/90187803/160561627-e8af6e8c-918e-496d-9677-5b19acb3c829.png)

## Acceptance Criteria

- [ ] to remove a list card needs confirmation 

## Tasks

- [ ] Add component Modal
- [ ] Testing
- [ ] Storybook
- [ ] Add function
- [ ] Check accessibility
- [ ] Adjust tests
- [ ] Test on Mobile
