### ISSUE TITLE
Improve UX - Refactor image upload

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#29]
## Value Proposition 

**As a** user
**I need to** have a smooth working image upload
**to be able to** look at the profile image of my cat and enjoy it

## Description
no description available

## Acceptance Criteria

- [ ] clear guidance what to do, to upload and remove a photo, with good positioning of the buttons
- [ ] the image keeps its aspect ratio

## Tasks

- [ ] Refactor Code
- [ ] Check accessibility
- [ ] Adjust tests
- [ ] Test on Mobile
