### ISSUE TITLE
Two pages with navigation

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#3]
## Value Proposition
**As a** cat owner 
**I need** to switch between two pages with lists of food my cat does or does not like to eat 
**to be able to** use both Information systems

## Description

![Bildschirmfoto 2022-03-04 um 17 23 33](https://user-images.githubusercontent.com/90187803/156800735-bba16aac-760f-49ec-8031-75eab6654ebd.png)

## Acceptance Criteria 
- [x] there are 2 pages, each containing a list, at one page with food my cat likes to eat, on the other page with food my cat doesn t like to eat - note: the new page is similar to that one from the userstory 1
- [x] there are 2 navigation buttons on a page
- [x] the active one has a different look
- [x] by clicking the corresponding button the suitable page renders
- [x] React Router is implemented
- [x] the navigation bar is not scrollable at the bottom of the viewport fixed
- [x] Error-Boundary is implemented

## Tasks
- [x] components/PageUnLikedFood
  - [x] Storybook
  - [x] Tests
  - [x] Styling
- [x] components/Navigation
  - [x] Storybook
  - [x] Tests
  - [x] React Router
  - [x] Styling
- [x] Error-Boundary
- [x] Check accessibility
- [x] Add to App
- [x] Check mobile view portrait/landscape
