### ISSUE TITLE
Code refactoring / Components

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#36]
## Value Proposition 

**As a** developer
**I need to** refactor my code
**to be able to** continue with cleaner code

## Description
no description available

## Acceptance Criteria

- [x] new ButtonBasicComponent, new HeaderComponent

## Tasks

- [x] Check Code
- [x] Refactor Code and add new Component for Header
- [x] Check accessibility
- [x] Adjust tests
- [x] Test on Mobile
