### ISSUE TITLE
Form for userinput

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#4]
## Value of Proposition
**As a** cat owner 
**I need** to fill in food data in a form 
**to be able to** fill up the prepared lists

## Description
<img width="300" alt="Bildschirmfoto 2022-03-03 um 14 02 49" src="https://user-images.githubusercontent.com/90187803/156570413-cfc3bce9-b272-477e-9e90-1e72c7bb0473.png">

## Acceptance Criteria

- [x] there is an explaining headline text, which is not fixed at the top of the viewport
- [x] there is a form
- [x] the form has 2 radio buttons depending on each other, attribute required
- [x] in the empty state the like-radio-button is active
- [x] there is a submit button for the save function rendered
- [x] clicking the submit button is clearing the form
- [x] the input of the user is added at the top of one of the two lists according to which radio button is active 
- [x] in empty state of the list pages is shown a message until the first item is produced by filling up the form

note: there is no validation of the user input atm

## Tasks

- [x] components/Button
  - [x] Storybook
  - [x] Tests
  - [x] Styling
- [x] components/Form
  - [x] Storybook
  - [x] Tests
  - [x] Styling
- [x] components/FormPage
  - [x] Storybook
  - [x] Tests  
- [x] Adjust navigation bar and Router
  - [x] Adjust Tests
- [x] Adjust ListPages
  - [x] Adjust Tests
- [x] Check accessibility
- [x] Add to App
- [x] Check at mobile in portrait and landscape modus
- [x] Write README file
