### ISSUE TITLE
Improve UX - Search for stored data when fill up the form

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#42]
## Value Proposition 

**As a** user
**I need to** have an embedded search for list entries
**to be able to** check out soon if i occasionally want to add cat food twice

## Description
no description available

## Acceptance Criteria

- [ ]  typing in the second form field will check, whether the combination "name of food" and "taste" already exists in the stored data
- [ ] the existing data are shown to the user as list cards similar to that in the disliked food and liked food pages

## Tasks

- [ ] Add function/s to check the stored data
- [ ] Add conditionally rendered list of cards with matching stored data
- [ ] Check accessibility
- [ ] Adjust tests
- [ ] Test on Mobile
