### ISSUE TITLE
Refactor form with React Hook Form

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#5]
## Value Proposition 

**As a** cat owner  
**I need to** have a larger and more comfortable form
**to be able to** save more information about cat food then before

## Description
![Bildschirmfoto 2022-03-17 um 22 26 41](https://user-images.githubusercontent.com/90187803/158897911-28dd655c-0d69-4d20-b82d-543b90ff9b3f.png)

## Acceptance Criteria

- [x] additional input field date
- [x] additional functions to inform the user about issues with the form or the input

## Tasks

- [x] Refactor Form with React Hook Form
- [x] Add input element for date of adding cat food to one of the lists
- [x] Add messages for user 
- [x] Adjust Tests
- [x] Check accessibility
- [x] Update README
