### ISSUE TITLE
Add a searchbar

### ISSUE THREAD

**Issue by ttaannjjaa** [ttaannjjaa/capstone-project#9]
## Value of Proposition
**As a** cat owner 
**I need** to have a searchbar in the list of cat food my cat does not like
**to be able to** find these data in my list more fasten when i am shopping cat food

## Description

<img width="324" alt="Bildschirmfoto 2022-03-13 um 11 15 47" src="https://user-images.githubusercontent.com/90187803/158054917-457ed0c3-85ae-4a4d-8a76-feb8a937b076.png">

## Acceptance Criteria

- [x] i can successfully search for cat food my cat does not like

note: there is no validation of the user input and modal atm

## Tasks

- [x] add a Searchbar to UnLikedFoodPage
  - [x] Storybook
  - [x] Tests
  - [x] Styling 
- [x] adjust README
- [x] Check accessibility
- [x] test on mobile portrait/landscape screen
